### PR TITLE
feat(cookie): cookie flags support and minor fixes

### PR DESCRIPTION
**Pull request by KhaledAlMana**
### Breaking changes 
None 

### Changes
- Support runtime configurations in playground (via .env) 
- fix response_types typo, changed to -> response_type
- fix scopes was pilings up caused by:
       - defaults were always appended to configured scopes
       - openid was added 3 times (from defaults, configurations, and issueClient parameters) 

UPDATE 1: 
- Added support for cookie flags and its documentation to be able to secure cookies if needed, with httpOnly, and secure flags or any other flags.

### CODE REVIEW

**Comment by aborn** [comment]
image

Get this error when pack.

**Comment by aborn** [comment]
temporary solution define **CookieSerializeOptions** again:
https://github.com/aborn/nuxt-openid-connect/blob/main/src/module.ts

If you can find better solution, change it! Thanks.

**Comment by KhaledAlMana** [comment]
Yes, Thanks, I've checked it already.
Totally fine for the moment while I figure out the better solution.

**Comment by KhaledAlMana** [comment]
Currenlty your temp solution is the cleanest.
There are many ways, but not very clean. It will require a bit more time than expected. 
I will try to take a deeper look into it another time.
Thanks for the fix, and the build.

**Pull request merged**
